# Generated by Django 4.1.5 on 2023-03-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_flat', models.CharField(max_length=2000)),
                ('price_flat', models.CharField(max_length=100000)),
                ('pub_date', models.DateTimeField(verbose_name='date_published_flat')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_house', models.CharField(max_length=2000)),
                ('price_house', models.CharField(max_length=100000)),
                ('pub_date', models.DateTimeField(verbose_name='date_published_flat')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_land', models.CharField(max_length=200)),
                ('price_land', models.CharField(max_length=100000)),
                ('pub_date', models.DateTimeField(verbose_name='date_published_land')),
            ],
        ),
    ]
